---
## from https://github.com/geerlingguy/ansible-role-apache/blob/master/.travis.yml
sudo: required

env:
  - distribution: centos
    version: 8
    init: /usr/lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    ANSIBLE_EXTRA_FLAGS: "'-e ansible_python_interpreter=/usr/bin/python3'"
  - distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
  - distribution: ubuntu
    version: 20.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    ANSIBLE_EXTRA_FLAGS: "'-e ansible_python_interpreter=/usr/bin/python3'"
  - distribution: ubuntu
    version: 18.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    ANSIBLE_EXTRA_FLAGS: "'-e ansible_python_interpreter=/usr/bin/python3'"
  - distribution: ubuntu
    version: 16.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
#  - distribution: alpine
#    version: 3.4
#    init: /sbin/init
#    run_opts: ""
#  - distribution: debian
#    version: 8
#    init: /lib/systemd/systemd
#    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"

services:
  - docker

before_install:
  # - sudo apt-get update
  - docker --version
  # Pull container
  - 'docker pull ${distribution}:${version}'
  - env
  - pwd
  - find -ls
  - "[ -f get-dependencies.sh ] && sh -x get-dependencies.sh"
  - cp test/travis/initctl_faker test/
  # Customize container
  - 'docker build --rm=true --file=test/travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible test'

script:
  - container_id=$(mktemp)
    # Run container in detached state
  - 'docker run --detach --volume="${PWD%/*}":/etc/ansible/roles:ro ${run_opts} ${distribution}-${version}:ansible "${init}" > "${container_id}"'

  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible --version'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/williamyeh.pcp/test/integration/default/default.yml --syntax-check ${ANSIBLE_EXTRA_FLAGS}'

  # Test role.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/williamyeh.pcp/test/integration/default/default.yml -vv ${ANSIBLE_EXTRA_FLAGS}'

  # Test role idempotence.
  - >
    docker exec "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/williamyeh.pcp/test/integration/default/default.yml ${ANSIBLE_EXTRA_FLAGS}
    | tee /tmp/idempotency.log
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)

  # serverspec tests
## travis/docker: Errno::EROFS: Read-only file system @ dir_s_mkdir - /etc/ansible/roles/williamyeh.pcp/test/integration/default/serverspec/.bundle
#  - 'sudo docker exec --tty "$(cat ${container_id})" /etc/ansible/roles/williamyeh.pcp/test/integration/default/serverspec/run-local-tests.sh'

after_failure:
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl status -l --no-pager'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm journalctl -xe --no-pager'
  - 'sudo docker exec --tty "$(cat ${container_id})" ansible -i inventory --connection=local -m setup localhost'

after_script:
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl status -l --no-pager pcp'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl status -l --no-pager pmwebd'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl status -l --no-pager pmcd'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl status -l --no-pager pmlogger'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm tail -1000 /var/log/pcp/pmlogger/pmlogger_daily-K.log'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm cat /usr/lib/systemd/system/pmlogger.service'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ls -alR /run/'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ps auxw'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ulimit -a'
  - 'ulimit -a'
  # Clean up
  - 'sudo docker stop "$(cat ${container_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
