---
# file: tasks/main.yml
# Top-level installer for PCP (Performance Co-Pilot).
#
# @see http://pcp.io/docs/installation.html
# @see http://www.pcp.io/books/PCP_UAG/html/LE43202-PARENT.html
#

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- name: delegate to APT system for installation
  include: use-apt.yml
  when: ansible_pkg_mgr == "apt"

- name: delegate to YUM system for installation
  include: use-yum.yml
  when: ansible_pkg_mgr == "yum"

- name: copy scripts to server
  copy: src="../files/{{ item }}"  dest="/tmp/"  mode="a+x"
  with_items:
    - check-pmda.py

- block:
    - name: check if there're still PMDAs needed to be installed
      command: /tmp/check-pmda.py '{{ pcp_pmcdconf_path }}' '{{ pcp_pmda }}'
      environment:
        LC_ALL: "en_US.UTF-8"
      changed_when: false
      register: pmda_info
      failed_when: pmda_info.rc > 0
    - name: install PMDAs
      file:
          path: /var/lib/pcp/pmdas/{{ item }}/.NeedInstall
          state: touch
      with_items: (pmda_info.stdout|from_json).add
      when: (pmda_info.stdout|from_json).ok  and  (pmda_info.stdout|from_json).changed
      notify: restart pcp
  when: pcp_pmcdconf_path is defined and pcp_pmcdconf_path != '' and pcp_pmda is defined and pcp_pmda != ''

- name: ensure service is enabled and started
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ pcp_services }}"

#/etc/pcp/pmrep/pmrep.conf, optional zabbix integration

- name: configure port listening for pmwebd
  lineinfile:
    dest: /etc/pcp/pmwebd/pmwebd.options
    line: "OPTIONS=\"$OPTIONS -p {{ pcp_pmwebd_port }}\""
    insertafter: '^#OPTIONS="-p 9999"  # port number'
    backup: yes
  notify:
    - restart pmwebd
## no pmwebd on standard centos
  when: ansible_os_family != "RedHat"

- include: security.yml
