---
# file: tasks/use-yum.yml
#
# Configure pcp from YUM repository.
#
# @see http://www.pcp.io/docs/installation.html
#

- name: install libselinux-python binary for Ansible to work
  yum:
    name: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-libselinux{% else %}libselinux-python{% endif %}"
    state: present
  register: pkg_result
  until: pkg_result is success

- block:
    - name: Add pcp bintray repository
      template: src=bintray-pcp.repo.j2 dest=/etc/yum.repos.d/bintray-pcp.repo
  when: pcp_repo is defined and pcp_repo == 'pcp'

- name: install PCP
  yum: name=pcp  update_cache=yes  state=present
  register: pkg_result
  until: pkg_result is success

- name: copy INIT script
  copy: src=/usr/share/pcp/lib/pcp dest=/etc/init.d/pcp remote_src=yes mode=0755
  when: ansible_service_mgr != 'systemd'
#  when: (ansible_os_family == "RedHat") and (ansible_distribution_major_version|int >= 7)
