---
# file: handlers/main.yml
#

- name: restart pcp
  service: name=pcp state=restarted

- name: stop pcp
  service: name=pcp state=stopped

- name: restart pmwebd
  service: name=pmwebd state=restarted

- name: restart pmcd
  service: name=pmcd state=restarted

